services:
  frontend:
    build:
      context: .
      target: ${TARGET}
    ports:
      - "5173:5173"
      - "80:80"
      - "9323:81"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}